"use client";

import type { FormEvent } from "react";
import { useMemo, useRef, useState } from "react";
import Webcam from "react-webcam";
import { useRouter } from "next/navigation";
import { apiFetch } from "../../lib/api";
import { clearToken } from "../../lib/storage";

export default function RegisterPage() {
  const router = useRouter();
  const webcamRef = useRef<Webcam | null>(null);

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [status, setStatus] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const cameraConstraints = useMemo(
    () => ({
      facingMode: "user",
      width: 640,
      height: 480,
    }),
    []
  );

  async function onRegister(e: FormEvent) {
    e.preventDefault();
    setBusy(true);
    setStatus(null);
    try {
      const faceImageBase64 = webcamRef.current?.getScreenshot();
      if (!faceImageBase64) throw new Error("Could not capture image from camera");

      setStatus("Encoding face on the server...");
      await apiFetch("/auth/register", {
        method: "POST",
        body: { name, email, password, faceImageBase64 },
      });
      clearToken();
      router.replace("/login");
    } catch (err) {
      setStatus(err instanceof Error ? err.message : "Registration failed");
    } finally {
      setBusy(false);
    }
  }

  return (
    <main className="mx-auto max-w-xl p-6">
      <h1 className="text-2xl font-semibold">Register (Face Capture)</h1>
      <p className="mt-2 text-sm text-neutral-600">Your face encoding is generated by the AI service.</p>

      <form className="mt-6 space-y-4" onSubmit={onRegister}>
        <label className="block">
          <span className="text-sm">Name</span>
          <input
            className="mt-1 w-full rounded border p-2"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
          />
        </label>
        <label className="block">
          <span className="text-sm">Email</span>
          <input
            className="mt-1 w-full rounded border p-2"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            type="email"
            required
          />
        </label>
        <label className="block">
          <span className="text-sm">Password</span>
          <input
            className="mt-1 w-full rounded border p-2"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            type="password"
            required
          />
        </label>

        <div className="rounded border p-3">
          <Webcam
            audio={false}
            ref={(r) => {
              webcamRef.current = r;
            }}
            screenshotFormat="image/jpeg"
            videoConstraints={cameraConstraints}
            style={{ width: "100%", borderRadius: 8 }}
          />
          <p className="mt-2 text-xs text-neutral-600">Keep a clear frontal face in frame.</p>
        </div>

        {status ? <div className="text-sm text-amber-700">{status}</div> : null}

        <button
          className="w-full rounded bg-neutral-900 px-4 py-2 text-white disabled:opacity-60"
          disabled={busy || !name || !email || !password}
          type="submit"
        >
          {busy ? "Registering..." : "Create account"}
        </button>

        <button className="w-full rounded border px-4 py-2" type="button" onClick={() => router.push("/login")} disabled={busy}>
          Back to login
        </button>
      </form>
    </main>
  );
}

